package com.syafrizal.dtsproyek1;

import com.syafrizal.dtsproyek1.models.Pokemon;

import java.util.ArrayList;
import java.util.List;

public class GenerateData {
        public static List<Pokemon> getPokemons(){
           List<Pokemon> pokemons = new ArrayList<>();

           pokemons.add(new Pokemon("Bulbasaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/bulbasaur.png","For some time after its birth, it grows by gaining nourishment from the seed on its back.",45,49,49,45,65,65,0.7,0,"Chlorophyll, Overgrow",6.9,87.5,12.5,5100,"Ivysaur"));
            pokemons.add(new Pokemon("Ivysaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/ivysaur.png","When the bud on its back starts swelling, a sweet aroma wafts to indicate the flowers coming bloom.",60,62,63,60,80,80,1,0,"Chlorophyll, Overgrow",13,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Venusaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/venusaur.png","After a rainy day, the flower on its back smells stronger. The scent attracts other Pokémon.",80,82,83,80,100,100,2,0,"Chlorophyll, Overgrow",100,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Bulbasaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/bulbasaur.png","For some time after its birth, it grows by gaining nourishment from the seed on its back.",45,49,49,45,65,65,0.7,0,"Chlorophyll, Overgrow",6.9,87.5,12.5,5100,"Ivysaur"));
            pokemons.add(new Pokemon("Ivysaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/ivysaur.png","When the bud on its back starts swelling, a sweet aroma wafts to indicate the flowers coming bloom.",60,62,63,60,80,80,1,0,"Chlorophyll, Overgrow",13,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Venusaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/venusaur.png","After a rainy day, the flower on its back smells stronger. The scent attracts other Pokémon.",80,82,83,80,100,100,2,0,"Chlorophyll, Overgrow",100,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Bulbasaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/bulbasaur.png","For some time after its birth, it grows by gaining nourishment from the seed on its back.",45,49,49,45,65,65,0.7,0,"Chlorophyll, Overgrow",6.9,87.5,12.5,5100,"Ivysaur"));
            pokemons.add(new Pokemon("Ivysaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/ivysaur.png","When the bud on its back starts swelling, a sweet aroma wafts to indicate the flowers coming bloom.",60,62,63,60,80,80,1,0,"Chlorophyll, Overgrow",13,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Venusaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/venusaur.png","After a rainy day, the flower on its back smells stronger. The scent attracts other Pokémon.",80,82,83,80,100,100,2,0,"Chlorophyll, Overgrow",100,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Bulbasaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/bulbasaur.png","For some time after its birth, it grows by gaining nourishment from the seed on its back.",45,49,49,45,65,65,0.7,0,"Chlorophyll, Overgrow",6.9,87.5,12.5,5100,"Ivysaur"));
            pokemons.add(new Pokemon("Ivysaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/ivysaur.png","When the bud on its back starts swelling, a sweet aroma wafts to indicate the flowers coming bloom.",60,62,63,60,80,80,1,0,"Chlorophyll, Overgrow",13,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Venusaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/venusaur.png","After a rainy day, the flower on its back smells stronger. The scent attracts other Pokémon.",80,82,83,80,100,100,2,0,"Chlorophyll, Overgrow",100,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Bulbasaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/bulbasaur.png","For some time after its birth, it grows by gaining nourishment from the seed on its back.",45,49,49,45,65,65,0.7,0,"Chlorophyll, Overgrow",6.9,87.5,12.5,5100,"Ivysaur"));
            pokemons.add(new Pokemon("Ivysaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/ivysaur.png","When the bud on its back starts swelling, a sweet aroma wafts to indicate the flowers coming bloom.",60,62,63,60,80,80,1,0,"Chlorophyll, Overgrow",13,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Venusaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/venusaur.png","After a rainy day, the flower on its back smells stronger. The scent attracts other Pokémon.",80,82,83,80,100,100,2,0,"Chlorophyll, Overgrow",100,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Bulbasaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/bulbasaur.png","For some time after its birth, it grows by gaining nourishment from the seed on its back.",45,49,49,45,65,65,0.7,0,"Chlorophyll, Overgrow",6.9,87.5,12.5,5100,"Ivysaur"));
            pokemons.add(new Pokemon("Ivysaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/ivysaur.png","When the bud on its back starts swelling, a sweet aroma wafts to indicate the flowers coming bloom.",60,62,63,60,80,80,1,0,"Chlorophyll, Overgrow",13,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Venusaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/venusaur.png","After a rainy day, the flower on its back smells stronger. The scent attracts other Pokémon.",80,82,83,80,100,100,2,0,"Chlorophyll, Overgrow",100,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Bulbasaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/bulbasaur.png","For some time after its birth, it grows by gaining nourishment from the seed on its back.",45,49,49,45,65,65,0.7,0,"Chlorophyll, Overgrow",6.9,87.5,12.5,5100,"Ivysaur"));
            pokemons.add(new Pokemon("Ivysaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/ivysaur.png","When the bud on its back starts swelling, a sweet aroma wafts to indicate the flowers coming bloom.",60,62,63,60,80,80,1,0,"Chlorophyll, Overgrow",13,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Venusaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/venusaur.png","After a rainy day, the flower on its back smells stronger. The scent attracts other Pokémon.",80,82,83,80,100,100,2,0,"Chlorophyll, Overgrow",100,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Bulbasaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/bulbasaur.png","For some time after its birth, it grows by gaining nourishment from the seed on its back.",45,49,49,45,65,65,0.7,0,"Chlorophyll, Overgrow",6.9,87.5,12.5,5100,"Ivysaur"));
            pokemons.add(new Pokemon("Ivysaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/ivysaur.png","When the bud on its back starts swelling, a sweet aroma wafts to indicate the flowers coming bloom.",60,62,63,60,80,80,1,0,"Chlorophyll, Overgrow",13,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Venusaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/venusaur.png","After a rainy day, the flower on its back smells stronger. The scent attracts other Pokémon.",80,82,83,80,100,100,2,0,"Chlorophyll, Overgrow",100,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Bulbasaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/bulbasaur.png","For some time after its birth, it grows by gaining nourishment from the seed on its back.",45,49,49,45,65,65,0.7,0,"Chlorophyll, Overgrow",6.9,87.5,12.5,5100,"Ivysaur"));
            pokemons.add(new Pokemon("Ivysaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/ivysaur.png","When the bud on its back starts swelling, a sweet aroma wafts to indicate the flowers coming bloom.",60,62,63,60,80,80,1,0,"Chlorophyll, Overgrow",13,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Venusaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/venusaur.png","After a rainy day, the flower on its back smells stronger. The scent attracts other Pokémon.",80,82,83,80,100,100,2,0,"Chlorophyll, Overgrow",100,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Bulbasaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/bulbasaur.png","For some time after its birth, it grows by gaining nourishment from the seed on its back.",45,49,49,45,65,65,0.7,0,"Chlorophyll, Overgrow",6.9,87.5,12.5,5100,"Ivysaur"));
            pokemons.add(new Pokemon("Ivysaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/ivysaur.png","When the bud on its back starts swelling, a sweet aroma wafts to indicate the flowers coming bloom.",60,62,63,60,80,80,1,0,"Chlorophyll, Overgrow",13,87.5,12.5,5100,"Venusaur"));
            pokemons.add(new Pokemon("Venusaur","Grass","https://img.pokemondb.net/sprites/omega-ruby-alpha-sapphire/dex/normal/venusaur.png","After a rainy day, the flower on its back smells stronger. The scent attracts other Pokémon.",80,82,83,80,100,100,2,0,"Chlorophyll, Overgrow",100,87.5,12.5,5100,"Venusaur"));

            return pokemons;

        }

}
